# Generated by Django 6.0.4 on 2026-05-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_premiumpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpayment',
            name='plan',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='subscription_reference',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
