# Generated by Django 6.0.4 on 2026-05-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_premiumpayment_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium_plan',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
    ]
